### ISSUE TITLE
data_format == "NCHW"

### ISSUE THREAD

**Issue by ghost** [carpedm20/pixel-rnn-tensorflow#3]
in your network.py:  
  if data_format == "NHWC":
      input_shape = [None, height, width, channel]
 elif data_format == "NCHW":
      input_shape = [None, height, width, channel]
 else:
      raise ValueError("Unknown data_format: %s" % data_format)
when data_format == "NCHW" input_shape =[None, channel, height, width] is right?

**Comment by carpedm20** [comment]
@pby5 wow, thanks!
