### ISSUE TITLE
mask A when apply for RGB channel

### ISSUE THREAD

**Issue by ghost** [carpedm20/pixel-rnn-tensorflow#4]
in your code about mask:
      mask = np.ones((kernel_h, kernel_w, channel, num_outputs), dtype=np.float32)

```
  mask[center_h, center_w+1: ,: ,:] = 0.
  mask[center_h+1:, :, :, :] = 0.

  if mask_type == 'a':
    mask[center_h,center_w,:,:] = 0.
```

but I confused that when apply for RGB channel,for example when predict G channel,
above code means the current pixel only relate to the generated pixels left and above in all three R G B channel, but in paper write "when predicting G channel, the value of the R channel can also be used as context in addition to the previously generated pixels." so is it right to contain all R channel pixel?

**Comment by ghost** [comment]
and I think for mask A, when predict G channel, use generated pixels left and above and all generated R pixels,is it right?

**Comment by carpedm20** [comment]
@pby5 Yes, you're right. The current code is wrong but it is no problem for MNIST data which only have a single channel. Before fixing this, I first need to fix #1 which I failed to do sequential generation even with the simple MNIST data. Then I'll fix #2 which is an update for RGB channels.

Now i'm working at [data_format_fix](https://github.com/carpedm20/pixel-rnn-tensorflow/tree/data_format_fix) branch which seems to be fix all of misused `NCHW` and `NHWC`. If you are confusing about masking, you can see useful examples [here](https://github.com/tensorflow/magenta/blob/master/magenta/reviews/pixelrnn.md).

**Comment by fanw52** [comment]
@carpedm20 ,Hello,recently,i read your code ,and i find the shape of the x_i is h x n x 4,however, Pixel rnn point out that x_i should be  h x n x 1, and i don't kown how to explain it ,or it's my error??

**Comment by fanw52** [comment]
@pby5 ,excuse me,do you know how to explain the question that i point out about the shape of x_i
