### ISSUE TITLE
output number of conv

### ISSUE THREAD

**Issue by ghost** [carpedm20/pixel-rnn-tensorflow#5]
when 7x7 conv mask A,what is the filter output number? and 3x3 conv layers,mask B,what is the filter output number?is it as paper said"the pixel cnn has 15 layers and h=128",does it equal h?and for relu followwd by 1x1 conv,what is the filter output number? I did not find parmters for this in paper,how did you set it?thanks

**Comment by carpedm20** [comment]
There are two feature dimension specified in the paper which is 1) h of LSTM or 3x3 conv layer and 2) ReLU 1x1 conv layer. The dimension of output of 7x7 conv is same as the input dimension of 1) h.

And if you're reading the code, you should read the code of [data_format_fix](https://github.com/carpedm20/pixel-rnn-tensorflow/tree/data_format_fix) branch. There are some critical fix I guess but its result is far from the result of the paper.
